version: '2'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: rucas1
      POSTGRES_USER: frangl
      POSTGRES_DB: base_datos
    ports:
      - 5432:5433

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  metabase:
    image: metabase/metabase
    restart: always
    ports:
      - 3000:3000
