version: '2'

services:
  nginx:
    build: nginx
    ports:
      - 80:80

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: rucas1
      POSTGRES_USER: frangl
      POSTGRES_DB: base_datos
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  metabase:
    image: metabase/metabase
    restart: always
    ports:
      - 3000:3000

  minio:
    image: minio/minio
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: rucas
      MINIO_SECRET_KEY: passwordMinio123
    command: server /data
