version: '2'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: ssadata
      POSTGRES_DB: base_datos
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  metabase:
    image: metabase/metabase
    restart: always
    ports:
      - 3000:3000
