version: '2'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: ssadata
      POSTGRES_DB: base_datos
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  metabase:
    image: metabase/metabase
    restart: always
    ports:
      - 3000:3000
      
  nginx:
    build: nginx
    ports:
        - "80:80"
        
  jupyter:
   image: jupyter/scipy-notebook
   restart: always
   ports:
       - 5000:8888
