version: '2'

services:
  nginx:
    build: nginx
    restart: always
    ports:
      - 80:80

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: passwordRucas123
      POSTGRES_USER: userRucas
      POSTGRES_DB: base_datos
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  metabase:
    image: metabase/metabase
    restart: always
    environment:
      - MB_SITE_URL=http://localhost/metabase/
    ports:
      - 3000:3000

  minio:
    image: minio/minio
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: userRucas
      MINIO_SECRET_KEY: passwordRucas123
    command: server /data
